version: '3'

services:
  lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./chordifier:/home/jovyan/work/chordifier
      - ./lab:/home/jovyan/work/lab
    environment:
      - JUPYTER_ENABLE_LAB=yes
